"""initial: users, swipes, matches, messages

Revision ID: 33a7bfe3fff4
Revises: 
Create Date: 2026-06-30 16:28:19.260603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '33a7bfe3fff4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.String(length=26), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('photos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('lat', sa.Double(), nullable=False),
    sa.Column('lon', sa.Double(), nullable=False),
    sa.Column('geohash', sa.String(length=12), nullable=False),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('matches',
    sa.Column('match_id', sa.String(length=52), nullable=False),
    sa.Column('user_a', sa.String(length=26), nullable=False),
    sa.Column('user_b', sa.String(length=26), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('preview_text', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_a'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['user_b'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_table('swipes',
    sa.Column('swiper_id', sa.String(length=26), nullable=False),
    sa.Column('swiped_id', sa.String(length=26), nullable=False),
    sa.Column('decision', sa.String(length=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['swiped_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['swiper_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('swiper_id', 'swiped_id')
    )
    op.create_table('messages',
    sa.Column('message_id', sa.String(length=26), nullable=False),
    sa.Column('match_id', sa.String(length=52), nullable=False),
    sa.Column('sender_id', sa.String(length=26), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    # Custom indexes from design.md §3
    op.create_index("idx_users_geohash", "users", ["geohash"], postgresql_ops={"geohash": "varchar_pattern_ops"})
    op.create_index("idx_users_gender_age", "users", ["gender", "age"])
    op.create_index("idx_swipes_swiped", "swipes", ["swiped_id", "decision"])
    op.create_index(
        "idx_matches_user_a_active",
        "matches",
        ["user_a", "is_active"],
        postgresql_where=sa.text("is_active = true"),
    )
    op.create_index(
        "idx_matches_user_b_active",
        "matches",
        ["user_b", "is_active"],
        postgresql_where=sa.text("is_active = true"),
    )
    op.create_index("idx_messages_match_time", "messages", ["match_id", sa.text("created_at DESC")])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index("idx_messages_match_time", table_name="messages")
    op.drop_index("idx_matches_user_b_active", table_name="matches")
    op.drop_index("idx_matches_user_a_active", table_name="matches")
    op.drop_index("idx_swipes_swiped", table_name="swipes")
    op.drop_index("idx_users_gender_age", table_name="users")
    op.drop_index("idx_users_geohash", table_name="users")
    op.drop_table('messages')
    op.drop_table('swipes')
    op.drop_table('matches')
    op.drop_table('users')
    # ### end Alembic commands ###
    # ### end Alembic commands ###
