name: Lint

on:
  push:
  pull_request:
  schedule:
    - cron: "0 9 * * *"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
        with:
          version: "0.8.0"
